config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'messages#index'

  resources :messages do
    collection do
      get :unread_messages
    end
  end
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :reciever, class_name: 'User', foreign_key: 'reciever_id'

  delegate :name, to: :sender, prefix: :sender
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recieved_messages, class_name: 'Message', foreign_key: 'reciever_id'
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'

  def unread_messages
    recieved_messages.where(read_at: nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_unread_messages

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password street city state country])
  end

  def check_unread_messages
    return unless user_signed_in?

    @notifications = current_user.unread_messages
  end
end

app/controllers/concerns/crud_concern.rb
module CrudConcern
  extend ActiveSupport::Concern

  ##################################################################
  #      This module take cares the CRUD controller methods        #
  #                                                                #
  # Note: add skip_before_action if you want to ignore any of the  #
  # above action to be loaded from module                          #
  ##################################################################

  included do
    before_action :init_resource
    before_action :load_resources, only: [:index]
    before_action :load_resource, only: [:new, :edit, :update, :destroy, :create, :show]
  end

  def index
  end

  def new
  end

  def show
  end

  def create
    if instance_variable_get("@#{@resource}").save(send("#{@resource}_params"))
      flash[:success] = "#{@resource.camelize} submitted successfully"
      redirect_to root_path
    else
      flash[:alert] = instance_variable_get("@#{@resource}").errors.full_messages.first
      redirect_back fallback_location: send("new_#{@resource}_path")
    end
  end

  def edit
  end

  def update
    if instance_variable_get("@#{@resource}").update!(send("#{@resource}_params"))
      flash[:success] = "Updated a #{@resource.camelize} successfully"
    end
    redirect_back fallback_location: send("edit_#{@resource}_path", instance_variable_get("@#{@resource}"))
  end

  def destroy
    respond_to do |format|
      format.html {
        if current_user.valid_password?(authenticate_params[:password])
          instance_variable_get("@#{@resource}").destroy
        else
          flash[:error] = 'Invalid Password'
        end
        redirect_to send("#{@resources}_path")
      }
      format.js {
        @path = send("#{@resource}_path", instance_variable_get("@#{@resource}"))
        render 'shared/delete'
      }
    end 
  end

  private

  def init_resource
    @resources = controller_name
    @resource = @resources.singularize
  end

  def load_resource
    if params[:action] == "create"
      instance_variable_set "@#{@resource}", @resources.classify.constantize.new(send("#{@resource}_params"))
    else
      instance_variable_set "@#{@resource}", @resources.classify.constantize.find_or_initialize_by(id: params[:id])
    end
  end

  def load_resources
    instance_variable_set "@#{@resources}", @resources.classify.constantize.unscoped.all.order(created_at: :desc).page(params[:page]).per(3)
  end

  def authenticate_params
    params.require(:authenticate).permit(:password)
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_message, only: [:show]

  def index
    @messages = current_user.recieved_messages.order(created_at: :desc).page(params[:page]).per(2)
  end

  def new
    @users = User.where.not(id: current_user.id).pluck(:name, :id)
    @message = Message.new
  end

  def create
    message = Message.new(message_params)
    if message.save
      flash[:info] = 'message send successfully'
    else
      flash[:error] = 'something went wrong'
    end
    redirect_to root_path
  end

  def show; end

  def unread_messages
    count = current_user.unread_messages.count
    render json: { count: count }
  end

  private

  def message_params
    params.require(:message).permit(:title, :content, :reciever_id).merge(sender_id: current_user.id)
  end

  def set_message
    @message = Message.find_by(id: params[:id], reciever_id: current_user.id)
    if @message.nil?
      flash[:info] = 'message not found'
      redirect_to(root_path)
    else
      @message.update(read_at: Time.now) if @message.read_at.nil?
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)
    resource.save
    if resource.save
      flash[:info] = 'registration completed successfully'
      redirect_to new_user_session_path
    else
      flash[:info] = 'something went wrong, try again'
      redirect_to new_user_registration
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :street, :city, :state, :country)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(text=nil, url=nil, icon=nil, wrapper_options={}, input_html={}, &block)
    url ||= text || ''
  	input_html[:class] = "#{input_html[:class]} #{'active' if current_page?(url)}"
  	content_tag(wrapper_options[:wrapper_elem] || :li, wrapper_options) do
  	  link_to url, input_html do
  	    if block_given?
  	      capture(&block)
  	    else
  	      content_tag(:i, nil, {class: icon.to_s}).concat(
  	        content_tag(:span, text)
  	      )
  	    end  
  	  end
  	end
  end

  def tree_link(text=nil, icon=nil, options={}, &block)
    (<<-HTML
      <li class="treeview">
        <a href="#">
          <i class='#{icon}'></i>
          <span>#{text}</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          #{capture(&block)}
        </ul>
      </li>
    HTML
    ).html_safe
  end

  def file_help name
    (<<-HTML
      <label for="#{name}"><span></span> <strong><i class="fa fa-upload"></i> Choose a file…</strong></label>
    HTML
    ).html_safe
  end

  def progress_bar(color=nil, percentage=0, bg=nil)
    (<<-HTML
    <td style="width: 300px">
      <div class="progress progress-xs progress-striped active">
        <div class="progress-bar progress-bar-#{color}" style="width: #{percentage}%"></div>
      </div>
    </td>
    <td>
      <span class="badge bg-#{bg}">#{percentage}%</span>
    </td>
    HTML
    ).html_safe
  end
  
  def admin?
    current_user.admin?
  end

end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
  def extract_text(html)
    ActionView::Base.full_sanitizer.sanitize(html)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>FORUM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>

  </head>

  <body class="hold-transition skin-purple-light sidebar-mini">
    <div class="wrapper">
      <% if user_signed_in? %>
      <header class="main-header">
        <a href="<%= root_path %>" class="logo">
          <span class="logo-mini"><b>F</b>RIENDS</span>
          <span class="logo-lg"><b>F</b>RIENDS</span>
        </a>
        <%= render 'shared/nav_menu' %>
      </header>
      <%= render "shared/side_menu" %>
      <div class="content-wrapper">
        <% flash.each do |key, value| %>
        <div class="alert alert-info alert-dismissible">
          <%= value %> <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
      <% else %>
      <%= yield %>
      <% end %>
    </div>
  </body>
  <script type="text/javascript">
    $(document).ready(function () {
      window.setInterval(function () {
        $.ajax({
          type: "get",
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          url: `/messages/unread_messages`,
          success: function (data) {
            $('span#notification').text(data.count)
          }
        });
   
      }, 60000);
    });
  </script>
</html>

<% cache 'modals' do %>
<div class="modal fade" id="new-form">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
<% end %>

app/views/messages/index.html.erb
<section class="content">
  <div class="row">
    <section class="content">  
      <% @messages.each do |message|%>
        <div class="box box-success">
          <div class="user-block">
            <%= image_tag('avatar.png') %>
            <span class="username">
              <a href="#"><%= message.sender_name %></a>
            </span>
            <span class="time pull-right"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(message.created_at) %> ago</span>
          </div>
          <div class="box-header">
            <br />
            <h3 class="box-title"><%= message.title %></h3>
          </div>
          <div class="box-body">
            <br />
            <p><%= truncate(extract_text(message.content), length: 200) %> <%= link_to  "read more..", message_path(message) %></p>
          </div>
          <div class="box-footer">
            <div class="row bottom_mrgn">
            </div>
            <ul class="list-inline">
              <li class="pull-right">
              </li>
            </ul>
          </div>
        </div>
      <% end %>      
      <%= paginate @messages %>
    </section>
  </div>
</section>

app/views/messages/new.html.erb
<section class="content">
  <div class="row">
    <section class="content">
      <div class="box box-warning">
        <div class="box-header with-border">
          <h3 class="box-title">Send Message</h3>
        </div>
        <div class="box-body">
          <%= form_for(@message, validate: true) do |f| %>
            <% if @message.errors.any? %>
              <% @message.errors.full_messages.each do |message| %>
                <span class="help-block"><%= message %></span>
              <% end %>
            <% end %>
            <div class="form-group">
              <%= f.label 'to*' %>
              <%= f.select(:reciever_id, @users, {include_blank: 'Please choose' },  { class: 'form-control expense' })%>

              <%= f.validate %>
            </div>
            <div class="form-group">
              <%= f.label 'title*' %>
              <%= f.text_field :title, class: 'form-control', placeholder: 'Title ...', required: true %>
              <%= f.validate %>
            </div>
            <div class="form-group">
              <%= f.label 'content*' %>
              <%= f.cktext_area :content, autocomplete: "off",:ckeditor => {:toolbar => 'mini'}, required: true ,'data-parsley-required-message'=>"Please enter a message" %>
              <%= f.validate %>
            </div>
            <div class="form-group">
              <%= f.submit 'Send', class: 'btn btn-primary float-right' %>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</section>

app/views/messages/show.html.erb
<div class="box box-success">
  <div class="box-header">
    <div class="user-block">
      <%= image_tag('avatar.png') %>
      <span class="username">
        <a href="#"><%= @message.sender_name %></a>
      </span>
      <span class="time pull-right"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(@message.created_at) %> ago</span>
    </div>
    <div>
      <br />
      <h3 class="box-title"><%= @message.title %></h3>
    </div>
  </div>
  <div class="box-body">
    <p><%= @message.content.html_safe %></p>
  </div>
  <div class="box-footer">
    <div class="row bottom_mrgn">
    </div>
    <ul class="list-inline">
      <li class="pull-right">
      </li>
    </ul>
  </div>
</div>

app/views/shared/_content_header.html.erb
<section class="content-header">
  <h1>
    Dashboard
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="#"><i class="fa fa-dashboard"></i> Home</a>
    </li>
    <li class="active">Dashboard</li>
  </ol>
</section>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs"><b>Version</b> 0.0.1</div>
  <strong
    >Copyright &copy;<%= Date.today.year %></strong
  >
  All rights reserved.
</footer>

app/views/shared/_nav_menu.html.erb
<nav class="navbar navbar-static-top">
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"> </a>
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge" id="notification"><%= @notifications.size %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
          <span class="dropdown-item dropdown-header"><%= @notifications.size %> Notifications</span>
          <div class="dropdown-divider"></div>
          
          <% @notifications.each do |notification| %>
            <%= link_to message_path(notification), class: 'dropdown-item' do %>
              <span><%= notification.sender_name %>:</span> <span> <%= truncate(extract_text(notification.content), length: 20) %> </span>
              <span class="float-right text-muted text-sm"><%= time_ago_in_words(notification.created_at) %> ago</span>
            <% end %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%link_to 'See All Notifications', messages_path%>
        </div>
      </li>
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= image_tag ('avatar.png'), class: "user-image" %>
          <span class="hidden-xs"><%= current_user.name %></span>
        </a>
        <ul class="dropdown-menu">
          <li class="user-header">
            <%= image_tag ('avatar.png'), class: "img-circle" %>
            <p>
              <%= current_user.email %> - Spericorn
              <small>Member since Nov. 2012</small>
            </p>
          </li>
          <li class="user-footer">
            <div class="pull-left"></div>
            <div class="pull-right">
              <%= link_to "Sign out",destroy_user_session_path, method: :delete,
              class: "btn btn-default btn-flat" %>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_side_menu.html.erb
<aside class="main-sidebar sidebar-dark-primary">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag ('avatar.png'), class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      <%= nav_link('Inbox', messages_path, 'fa fa-envelope') %>
      <%= nav_link('Compose', new_message_path, 'fa fa-at') %>
    </ul>
  </section>
</aside>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>